[package]
name = "_pytucanos"
version = "0.1.0"
edition = "2021"

[lib]
name = "_pytucanos"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.20"
ndarray = "0.15.6"
numpy = "0.20"
pyo3 = { version = "0.20", features = ["extension-module", "multiple-pymethods"] }
pyo3-log = "0.9"
tucanos = { git = "https://github.com/tucanos/tucanos.git", rev = "110f81a" }

[features]
nlopt = ["tucanos/nlopt"]
meshb = ["tucanos/meshb"]
