[package]
name = "_pytucanos"
version = "0.1.0"
edition = "2021"

[lib]
name = "_pytucanos"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.17"
ndarray = "0.15.6"
numpy = "0.18.0"
pyo3 = { version = "0.18.0", features = ["extension-module", "multiple-pymethods"] }
pyo3-log = "0.8.1"
tucanos = { git = "https://github.com/tucanos/tucanos.git", rev = "4a59fc10" }

[features]
accelerate = ["tucanos/accelerate"]
netlib = ["tucanos/netlib"]
openblas = ["tucanos/openblas"]
intel-mkl = ["tucanos/intel-mkl"]
nlopt = ["tucanos/nlopt"]
libmeshb-sys = ["tucanos/libmeshb-sys"]
