name: Install and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  REMESH_LIBRARIES: lapack

permissions:
  contents: read
  packages: read
  pull-requests: read
  checks: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libmetis-dev libscotch-dev liblapack-dev
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
        toolchain: nightly
        override: true
    - name: Rust cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-nightly-
    - name: Run clippy
      uses: clechasseur/rs-clippy-check@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Run pip install & unittests
      run: |
        pip install .
        cd
        python -c "import pytucanos; assert not pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert not pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
    - name: Run pip install & unittests (metis)
      run: |
        pip install -C metis=true .
        cd
        python -c "import pytucanos; assert pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert not pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
    - name: Run pip install & unittests (scotch)
      run: |
        pip install -C scotch=true .
        cd
        python -c "import pytucanos; assert not pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libmetis-dev libscotch-dev liblapack-dev
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
        override: true
    - name: Rust cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-stable-
    - name: Run clippy
      uses: clechasseur/rs-clippy-check@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Run pip install & unittests
      run: |
        pip install .
        cd
        python -c "import pytucanos; assert not pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert not pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
    - name: Run pip install & unittests (metis)
      run: |
        pip install -C metis=true .
        cd
        python -c "import pytucanos; assert pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert not pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
    - name: Run pip install & unittests (scotch)
      run: |
        pip install -C scotch=true .
        cd
        python -c "import pytucanos; assert not pytucanos.HAVE_METIS"
        python -c "import pytucanos; assert pytucanos.HAVE_SCOTCH"
        python -m unittest discover pytucanos -v
